server:
  port: 8090

spring:
  main:
    web-application-type: reactive
  datasource:
    mysql:

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:13306/ai_learning?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
      type-class-name: com.zaxxer.hikari.HikariDataSource
      pool:
        pool-name: Retail_HikariCP
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
    pgvector:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    model:
      chat: none
      embedding: none
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none

    mcp:
    server:
    # 启用 stdio 传输（允许通过 STDIO 连接 MCP 客户端）
    stdio: true


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  level:
    root: info
  config: classpath:logback-spring.xml

ai:
    memory:
      compression:
        model-id: 7c5d376d-3bf6-41dd-a5dc-a7390ae09a18
      ltm:
        default-embedding-model-id: a0ab2e45-948e-46ec-95b2-7c7da0281daf